name: Regression

on:
  schedule: 
    - cron: '0 5 * * *' # every day at 07:00 UTC

  workflow_dispatch: # Run manually

jobs:
  regression:
    uses: SkylineCommunications/BOOST-DailyRegression/.github/workflows/regression.yml@main
    with:
      workflow-name: connector-ci-cd.yml
    secrets:
      msteams-webhook: ${{ secrets.TEAMS_WEBHOOK }}
  regression-oidc:
    uses: SkylineCommunications/BOOST-DailyRegression/.github/workflows/regression.yml@main
    needs: regression
    with:
      workflow-name: connector-ci-cd-oidc.yml
    secrets:
      msteams-webhook: ${{ secrets.TEAMS_WEBHOOK }}